/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ConfigurationObjectPageObjectPage journey");

        opaTest("Navigate to ConfigurationObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheConfigurationList.onFilterBar().iExecuteSearch();

            Then.onTheConfigurationList.onTable().iCheckRows();
            When.onTheConfigurationList.onTable().iPressRow(0);

            Then.onTheConfigurationObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheConfigurationObjectPage.iCheckNumberOfSections(2);
            When.onTheConfigurationObjectPage.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheConfigurationObjectPage.iCheckSection({ section: "GeneralInfo" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Id" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Description" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Key1" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedBy" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CreatedAt" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedBy" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LastChangedAt" });
            Then.onTheConfigurationObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "LocalLastChangedAt" });
            When.onTheConfigurationObjectPage.iPressSectionIconTabFilterButton("TechnicalInfo");
            Then.onTheConfigurationObjectPage.iCheckSection({ section: "TechnicalInfo" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});