/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ConfigurationListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheConfigurationList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Configuration ID");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Description");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Created By");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Created On");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Changed By");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Changed On");
            Then.onTheConfigurationList.onFilterBar().iCheckFilterField("Changed On");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheConfigurationList.onTable().iCheckColumns(undefined, {"Id":{"header":"Configuration ID"},"Description":{"header":"Description"},"Key1":{"header":"Configuration Key"},"CreatedBy":{"header":"Created By"},"CreatedAt":{"header":"Created On"},"LastChangedBy":{"header":"Changed By"},"LastChangedAt":{"header":"Changed On"},"LocalLastChangedAt":{"header":"Changed On"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheConfigurationList.onFilterBar().iExecuteSearch();
            
            Then.onTheConfigurationList.onTable().iCheckRows();

            When.onTheConfigurationList.onTable().iPressRow(0);
            Then.onTheConfigurationObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});